@startuml

autonumber

User -> Client: Give directory paths and connection info
Client -> Server: Send TCP connection request
Client <-- Server: Accept TCP connection

Client -> Server: Send directory paths

loop Received directories
  Server -> System: List directory contents
  alt Directory valid
    Server <-- System: Return files in a directory
  else Directory invalid
    Server <-- System: Return error message
  end
end

Client <-- Server: Send accumulated listings
User <-- Client: Display accumulated listings

@enduml
