@startuml

autonumber

User -> Client: Give directory paths and connection info
Client -> Server: Send TCP connection request
Client <-- Server: Accept TCP connection

loop Specified directories

Client -> Server: Send path
Server -> System: List directory

  alt Directory valid
    Server <-- System: Return files in a directory
    Client <-- Server: Send list of files
  else Directory invalid
    Server <-- System: Return error code
    Client <-- Server: Send error message
  end

end

User <-- Client: Display the accumulated listings

@enduml
