@startuml

left to right direction

actor User as user
actor "Local Client" <<Software>> as client
actor "Remote Server" <<Software>> as server

rectangle {
  user -- (browse remote directories)
  (browse remote directories) .> (print directory listings) : include
  (print directory listings) -- client
  (browse remote directories) .> (get directory listings) : include
  (get directory listings) -- client
  (get directory listings) -- server
}

@enduml
