---
title: "Результаты моделирования"
output: word_document
---

```{r setup, include = FALSE}
library(jsonlite)
library(dplyr)
library(flextable)
library(ggplot2)
```

## Исследование влияния загрузки на длительность переходного режима

Таблица 1. Результаты моделирования варианта 1

```{r, echo = FALSE}
results <- jsonlite::fromJSON("results.json")
table1 <- filter(results, model == 0)

table1 %>%
  filter(task_count %in% c(100, 300, 1000, 3000, 5000, 7000, 9000, 10000)) %>%
  select(task_count, utilization, loss_probability, mean_wait_time, mean_residence_time) %>%
  flextable() %>%
  set_header_labels(
    task_count = "Заявок",
    utilization = "Загрузка",
    loss_probability = "Вер. потери",
    mean_wait_time = "Время ожидания",
    mean_residence_time = "Время пребывания") %>%
  theme_box() %>%
  autofit()
```
```{r, echo = FALSE}
ggplot(table1, aes(x = task_count)) +
  geom_line(aes(y = mean_wait_time)) +
  labs(x = "Число заявок", y = "Среднее время ожидания")
```

График 1. Зависимость среднего времени ожидания от числа заявок
