---
title: "Lab1"
output: html_notebook
---

# Dependencies

```{r}
install.packages("readxl")
library("readxl")
```

# Distribution Properties

```{r}
confeps <- function(sample, conf) {
  int <- t.test(sample, conf.level = conf)$conf.int
  (int[2] - int[1]) / 2
}

distprops <- function(data, samplecnts = c(10, 50, 100, 200, 300)) {
  samples <- sapply(samplecnts, function(cnt) data[1:cnt])
  data.frame(
    row.names = samplecnts,
    means = sapply(samples, mean),
    epsilon90 = sapply(samples, confeps, conf = 0.9),
    epsilon95 = sapply(samples, confeps, conf = 0.95),
    epsilon99 = sapply(samples, confeps, conf = 0.99),
    variances = sapply(samples, var),
    stddevs = sapply(samples, sd),
    cfvars = sapply(samples, function(s) sd(s) / mean(s))
  )
}

writeprops <- function(props) {
  colnames(props) <- c("Мат. ож.", "Дов. инт (0.9)", "Дов. инт (0.95)", "Дов. инт. (0.99)", "Дисперсия", "С. к. о.", "К-т вариации")
  write.csv(format(t(props), ditigs = 4))
}
```

# Lab Data

```{r}
labdata <- unlist(read_excel("3302_Лабушев-Нестеров.xlsx", col_names = FALSE))
writeprops(distprops(labdata))
```

## Plot

```{r}
plot(labdata, type = "h", main = "График 1. Значения исходной последовательности", xlab = "Порядковый номер элемента", ylab = "Значение элемента")
```

# Autocorrelation

```{r}
writecf <- function(cfs) {
  frame <- data.frame(cfs, row.names = 1:10)
  write.table(format(t(frame), digits = 3, trim = TRUE), sep = ",", row.names = FALSE)
}

labacf <- acf(labdata, plot = FALSE)[1:10]$acf
writecf(labacf)
```

## Plot

```{r}
plot(labacf, type = "b", main = "График 2. Автокорреляция исходной последовательности", xlab = "Сдвиг последовательности", ylab = "Коэффициент автокорреляции")
```

# Histogram

```{r}
hist(labdata, breaks = 100, main = "График 3. Гистограмма распределения частот последовательности", xlab = "Интервалы значений", ylab = "Частота")
```

# Approximation

Erlang distribution: $\nu = \frac{1}{\sqrt{k}}, k \in N \implies k = \lceil \frac{1}{\nu^2} \rceil$

```{r}
cfvar <- sd(labdata) / mean(labdata)
k <- ceiling(1 / cfvar^2)
approxdata <- rgamma(length(labdata), shape = k, scale = mean(labdata) / k)
writeprops(distprops(approxdata))
```

## Probability Densitiy Functions Comparison Plot

```{r}
labpdf <- density(labdata, n = 60, bw = "SJ")
approxpdf <- density(approxdata, bw = "SJ")
plot(labpdf$x, labpdf$y, col = "black", lwd = 2, type = "h", main = "График 4. Сравнение функций плотности", xlab = "Интервалы", ylab = "Плотность")
lines(approxpdf$x, approxpdf$y, col = "red", lwd = 2)
legend(60, 0.08, legend = c("Исходные данные", "Аппроксимация"), col = c("black", "red"), lwd = 2, xjust = 1)
```

## Autocorrelation

```{r}
approxacf <- acf(approxdata, plot = FALSE)[1:10]$acf
writecf(approxacf)
plot(approxacf, type = "b", main = "График 5. Автокорреляция случайной последовательности", xlab = "Сдвиг последовательности", ylab = "Коэффициент автокорреляции")
```

## Cross-Correlation of Source and Generated Series

```{r}
labccf <- ccf(labdata, approxdata, plot = FALSE)[1:10]$acf
writecf(labccf)
```